CUDA_VISIBLE_DEVICES=3 python train_eager.py \
    --data-root /PATH/TO/ImageNet \
    --data ImageNet \
    --arch msdnet \
    --batch-size 256 \
    --epochs 90 \
    --nBlocks 5 \
    --stepmode even \
    --step 4 \
    --base 4 \
    --nChannels 32 \
    --growthRate 16 \
    --grFactor 1-2-4-4 \
    --bnFactor 1-2-4-4 \
    --use-valid
